LITE-28158: Allow multiple slots to be exposed by widgets
cloudblue/connect-ui-toolkit pull request #20
Opened 2023-07-24 14:44 UTC by arnaugiralt

2023-07-25 15:32 UTC, theConscience commented on src/core/registerWidget.js
> +};
So, you mixed in injector bus and store to each widget here, right?

2023-07-25 15:36 UTC, theConscience commented on src/widgets/tabs/widget.vue
> +      this.$el.dispatchEvent(new CustomEvent('click-tab', { detail: tab.value, bubbles: true, composed: true }));
so instead of boiler and bus we should now dispatch custom dom event now?

2023-07-25 15:37 UTC, theConscience requested changes
[cod-c] 

Please answer above comments. Thx.

2023-08-02 20:15 UTC, arnaugiralt commented on src/core/registerWidget.js
> +};
Exactly. We just add these mixins to our component and Vue's [`defineCustomElement`](https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue) function takes care of creating a custom element on top of it.

In practice, we get the same result as before: injector, bus and store are available to be used in our components.

2023-08-02 20:23 UTC, arnaugiralt commented on src/widgets/tab/widget.vue
> +      this.$bus.emit('click-tab', this.tab);
Not really. Before this PR, `$boiler` was responsible of dealing with inter-component communication, in a `parent <–> child` way (bidirectional).

Internally, it is a quite complex pub-sub system to deal with events, which we don't really need now that we use Vue's `defineCustomElement` function to wrap our components. Regular DOM events now work to cover most cases, and, in case that communication is not from `child –> parent`, we can use the new `$bus`, which is a very simple event bus (see [the eventBus file](https://github.com/cloudblue/connect-ui-toolkit/pull/20/files#diff-f8f7d1a2edd77350c7bff34778974d37de4f534f4584013249eda5c808f37ef2R4) or [mitt's documentation](https://github.com/developit/mitt)). It acts as a global event bus, not namespaced for now for the sake of keeping things simple, but we could add that functionality if needed.

2023-08-02 20:25 UTC, arnaugiralt commented on src/widgets/tab/widget.vue
> +      this.$bus.emit('click-tab', this.tab);
And no, we don't have other entities named `$bus` in this repo. We do in others (like the SPA), where the concept is basically the same. Have a global event bus that can be used to send/subscribe events from anywhere.

2023-08-02 22:37 UTC, arnaugiralt commented on src/widgets/tabs/widget.vue
> +      this.$el.dispatchEvent(new CustomEvent('click-tab', { detail: tab.value, bubbles: true, composed: true }));
It depends on the scenario, but in general terms I'd say it should be the preferred way, mainly because it allows us to implement web components the same way we do with Vue components or regular html files, with simple event listeners.

Picture the following hypothetical scenario: We have a component in the toolkit, `UiError`, that we use to display errors, and emits a `"closed"` event when dismissed.
Currently, if we are using the toolkit in an extension and want to use the `UiError` in our code, we would need to register our extension components with the toolkit in order to be able to listen to that event by using the `$boiler`, which makes it pretty cumbersome.
With my changes you could simply add a listener to the `UiError` component and be done with it. Let's see that in an example, using Vue would be as simple as this:
```vue
<template>
  <ui-error @dismissed="onErrorDismissed" />
</template>
```
Or, if we are just using html and vanilla js:
```html
<html>
<body>
    <ui-error id="error"></ui-error>
    <script>
      document.querySelector('#error').addEventListener('dismissed', ({ detail }) => ...);
    </script>
</body>
</html>
```
These examples could be provided in any modern framework or library, since they all support adding DOM event listeners to the elements.

So, in my opinion, the best way, design-wise, is to use custom events. It is the web's default design, and every major framework also uses them, so using them is a no brainer for the developers, no matter the framework they choose to use over our toolkit.

Anyway, this could be discussed further, of course. Let me know what you think!

2023-08-08 07:20 UTC, riazhski approved these changes

2023-08-08 11:28 UTC, victor-cuevas approved these changes

2023-08-08 15:24 UTC, theConscience commented on src/core/registerWidget.js
> +};
is it backwards compatible with an old version-oriented extensions?

2023-08-08 15:26 UTC, theConscience commented on src/widgets/tab/widget.vue
> +      this.$bus.emit('click-tab', this.tab);
okay. but should we rewrite our extensions if they are explicitly uses $boiler.**** now?

2023-08-08 15:28 UTC, arnaugiralt commented on src/core/registerWidget.js
> +};
Nope, this is a breaking change. It will be released into a new major version, so the current extensions will continue to work as expected, using the already released version.

2023-08-08 15:31 UTC, arnaugiralt commented on src/widgets/tab/widget.vue
> +      this.$bus.emit('click-tab', this.tab);
Yes, if an extension wants to use the new version, it will need to be refactored. But since the change will be released into its own major version release, extensions will continue to work just fine.

2023-08-10 08:16 UTC, arnaugiralt commented
Hi, ignore the comments about dismissing reviews with "The merge-base changed after approval", they appear because I merged another PR and Github automatically created these comments.

Please take a look at the PR again! Would be nice to merge it before my vacations.

2023-08-10 08:32 UTC, theConscience submitted a review, later dismissed
Everything fine

2023-08-10 09:06 UTC, theConscience submitted a review, later dismissed

2023-08-10 09:12 UTC, riazhski submitted a review, later dismissed

2023-08-10 09:23 UTC, arnaugiralt commented
There are some issues with github automatically dismissing your approvals... will create another PR

2023-08-10 09:23 UTC, closed without merging