Add simple dialog
cloudblue/connect-ui-toolkit pull request #88
Opened 2024-05-06 15:12 UTC by nerimartinez

![image](https://github.com/cloudblue/connect-ui-toolkit/assets/12262532/f5d27109-4221-4ac2-904b-e10de99ff087)

2024-05-06 15:30 UTC, arnaugiralt requested changes

2024-05-06 15:33 UTC, nerimartinez commented on components/src/widgets/dialog/widget.vue
> +import { computed } from 'vue';
wow, I was sure I added it! thanks!

2024-05-07 16:22 UTC, arnaugiralt commented
> could you please check it out why in documentation tab we don't see the dialog correctly??
> 
> <img alt="Screenshot 2024-05-07 at 15 23 54" width="1083" src="https://private-user-images.githubusercontent.com/52078551/328539095-02483f76-30b9-422e-afbf-cb2241a70121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTkxNDcsIm5iZiI6MTcxNTA5ODg0NywicGF0aCI6Ii81MjA3ODU1MS8zMjg1MzkwOTUtMDI0ODNmNzYtMzBiOS00MjJlLWFmYmYtY2IyMjQxYTcwMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE2MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjY2Q5ZThlZGZkNDNkOThmNzZiYWE0ZTE1N2QwNTNjM2U3NDViYTk2YTdmZDE1OTUwMWMwMjUzMmZmY2U4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z9Zx6H0q4ThnOZPh3Q9XnlynLGiGwR81qvYOc5Sb0os">

yep, also the title is displayed with weird margins in the storybook, I guess that's because we need to set the margin to 0.

2024-05-08 10:32 UTC, paulinaczybir approved these changes

2024-05-08 10:41 UTC, arnaugiralt approved these changes

2024-05-08 10:41 UTC, merged