Feature/lite 29730 migrate to esm and from webpack to vite
cloudblue/connect-ui-toolkit pull request #90
Opened 2024-05-08 17:34 UTC by paulinaczybir

- Use ES Modules instead of CommonJs
- Replace webpack build with vite build
- replace testing library from jest to vitest
- upgrade storybook 8 and add support to work with vite

2024-05-14 13:44 UTC, nerimartinez commented on components/src/core/injector/core/injectorFactory.js
> +import { clone, has } from '~core/helpers.js';
why? just being curious

2024-05-14 13:47 UTC, nerimartinez commented on components/src/core/injector/index.spec.js
>  import injectorFactory from './core/injectorFactory';
*****

2024-05-14 13:47 UTC, nerimartinez commented on components/src/core/injector/index.js
> +import injectorFactory from './core/injectorFactory.js';
in the spec is imported without `.js`. why?

2024-05-14 13:48 UTC, nerimartinez submitted a review, later dismissed

2024-05-14 15:45 UTC, arnaugiralt commented
> IMPROVEMENTS in the future:
> 
> bringing back svg mock to not load all icons for tests (didn't find way to replace by vitest config how vite deals with icons)
> storybook initial loading time is surprisingly long :(

Could you add these improvements as new subtasks in the UI Toolkit JIRA US?

2024-05-14 16:01 UTC, arnaugiralt requested changes

2024-05-16 16:43 UTC, paulinaczybir commented on components/src/core/injector/core/injectorFactory.js
> +import { clone, has } from '~core/helpers.js';
This is not needed anymore, so I deleted it to unify imports. It was leftover from the migrating process. Thanks!

2024-05-16 16:44 UTC, paulinaczybir commented on components/src/core/injector/index.js
> +import injectorFactory from './core/injectorFactory.js';
This is not needed anymore, so I deleted it to unify imports. It was leftover from the migrating process. Thanks!

2024-05-16 16:44 UTC, paulinaczybir commented on .github/workflows/publish.yml
> +        run: npm i
Thanks, I brought back the npm ci, this change is not relevant anymore.

2024-05-16 16:45 UTC, paulinaczybir commented on package.json
> +    "vite": "^5.1.6",
Done, thanks!

2024-05-17 08:05 UTC, arnaugiralt approved these changes

2024-05-17 08:06 UTC, merged